### ISSUE TITLE
Failed to add transport node

### ISSUE THREAD

**Issue by lxiaopei** [vmware/nsx-t-datacenter-ci-pipelines#47] opened 2019-04-25 08:13 UTC
See  http://10.40.1.59:8080/teams/main/pipelines/nsx-t-install/jobs/add-nsx-t-routers/builds/2

**Comment by Dyanngg** [comment] 2019-04-25 17:43
Hi @lxiaopei ,
Please only paste the error printout on GitHub issues next time for security reasons. 
The cause of the issue is node deployments now takes a list of IPs rather than one IP. This has been fixed in a recent patch. Still, this NSX installation on ESX is for additional ESX to be installed in the specified cluster, otherwise a 'Node with same ip .... already exists' error will be thrown.

**Closed by Dyanngg** 2019-04-25 17:43 UTC
